license_id: "cc-by-igo"
caveats: "Reliability and accuracy depend on the sampling design and size of the basic variables and these might differ significantly between countries just as the use of data sources, definitions and methods. The accuracy of an indicator is very much dependent on the accuracy of the basic variables that make up the indicator."
methodology: "Registry"
dataset_source: "FAOSTAT"
package_creator: "mcarans"
private: False  # has to be True or False
