# Collector specific configuration
filelist_url: "http://fenixservices.fao.org/faostat/static/bulkdownloads/datasets_E.json"
countrygroup_url: "config/FAOSTAT_CountryGroups.csv"
showcase_base_url: "http://www.fao.org/faostat/en/#country/"
indicatorsetnames:
  - category: "Food Security"
    title: "Food Security Indicators"
    quickcharts:
      code: "FS"
      indicators:
        - code: "21010"
          title: "Average dietary energy supply adequacy"
          unit: "Percentage"
        - code: "210041"
          title: "Prevalence of undernourishment"
          unit: "Percentage"
        - code: "21034"
          title: "Percentage of arable land equipped for irrigation"
          unit: "Percentage"
  - category: "Prices"
    title: "Food Prices"
    quickcharts:
      code: "CP"
      indicators:
        - code: "23013"
          title: "Consumer Prices, Food"
          unit: "Consumer Prices Index (2010 = 100)"
        - code: "23012"
          title: "Consumer Prices, General"
          unit: "Consumer Prices Index (2010 = 100)"
